/**
 * Generates src/environments/environment.prod.ts from Vercel environment variables.
 * Run before `ng build` via the `vercel-build` npm script.
 *
 * Required Vercel env vars:
 *   TRANSLOADIT_KEY
 *   TRANSLOADIT_TEMPLATE_ID
 *   GOOGLE_API_KEY
 *   GOOGLE_CLIENT_ID
 *   GOOGLE_PROJECT_NUMBER
 *   DROPBOX_APP_KEY
 *   FACEBOOK_APP_ID
 *   BOX_CLIENT_ID
 */
const fs = require('fs');
const path = require('path');

function required(name) {
  const value = process.env[name];
  if (!value) {
    console.error(`[generate-env] Missing required environment variable: ${name}`);
    process.exit(1);
  }
  return value;
}

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit manually.
export const environment = {
  production: true,
  transloadit: {
    key: '${required('TRANSLOADIT_KEY')}',
    templateId: '${required('TRANSLOADIT_TEMPLATE_ID')}',
  },
  googleDrive: {
    apiKey: '${required('GOOGLE_API_KEY')}',
    clientId: '${required('GOOGLE_CLIENT_ID')}',
    projectNumber: '${required('GOOGLE_PROJECT_NUMBER')}',
  },
  dropbox: {
    appKey: '${required('DROPBOX_APP_KEY')}',
  },
  facebook: {
    appId: '${required('FACEBOOK_APP_ID')}',
  },
  box: {
    clientId: '${required('BOX_CLIENT_ID')}',
    clientSecret: '',
  },
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[generate-env] Wrote', outPath);
